AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Shopping Cart - SAM template (complete)

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CartUserPool.Arn

  CartTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cart-table
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  CartQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: cart-queue-dlq

  CartQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: cart-queue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CartQueueDLQ.Arn
        maxReceiveCount: 5

  AddToCartFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/addToCart.handler
      CodeUri: .
      Events:
        AddApi:
          Type: Api
          Properties:
            Path: /cart
            Method: post
            RestApiId: !Ref Api
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CartTable

  ListCartFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/listCart.handler
      CodeUri: .
      Events:
        ListApi:
          Type: Api
          Properties:
            Path: /cart/{userId}
            Method: get
            RestApiId: !Ref Api
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CartTable

  ProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/products.handler
      CodeUri: .
      Events:
        ProductsApi:
          Type: Api
          Properties:
            Path: /products
            Method: get
            RestApiId: !Ref Api
        ProductApi:
          Type: Api
          Properties:
            Path: /products/{productId}
            Method: get
            RestApiId: !Ref Api

  UpdateCartFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/updateCart.handler
      CodeUri: .
      Events:
        UpdateApi:
          Type: Api
          Properties:
            Path: /cart
            Method: put
            RestApiId: !Ref Api
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CartTable

  MigrateCartFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/migrateCart.handler
      CodeUri: .
      Environment:
        Variables:
          QUEUE_URL: !Ref CartQueue
      Events:
        MigrateApi:
          Type: Api
          Properties:
            Path: /cart/migrate
            Method: post
            RestApiId: !Ref Api
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CartTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt CartQueue.QueueName

  DeleteFromCartFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/deleteFromCart.handler
      CodeUri: .
      Events:
        DeleteQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt CartQueue.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CartTable

  CheckoutCartFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/checkoutCart.handler
      CodeUri: .
      Events:
        CheckoutApi:
          Type: Api
          Properties:
            Path: /cart/checkout
            Method: post
            RestApiId: !Ref Api
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CartTable

  AggregatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/aggregator.handler
      CodeUri: .
      Events:
        CartStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt CartTable.StreamArn
            StartingPosition: TRIM_HORIZON
      Policies:
        - CloudWatchPutMetricPolicy: {}

  # Cognito User Pool for protecting sensitive endpoints
  CartUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: cart-user-pool
      AutoVerifiedAttributes:
        - email

  CartUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: cart-user-pool-client
      UserPoolId: !Ref CartUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

Outputs:
  ApiUrl:
    Description: API Gateway endpoint for the dev stage
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/dev/"
